syntax = "proto3";
import "google/protobuf/timestamp.proto";

option csharp_namespace = "LPS.Protos.Shared";
package cooling;

service CoolingProtoService {
    rpc Report(CoolingReportRequest) returns (CoolingReportResponse);
}

message CoolingReportRequest {
    repeated CoolingStateUpdate updates = 1;
}

message CoolingStateUpdate {
    string iteration_id = 1;
    string host_name = 2;
    string source = 3;
    google.protobuf.Timestamp start = 4;
    google.protobuf.Timestamp end = 5;
    string node_id = 6;
    string machine_name = 7;
    string reason = 8;
    bool is_active = 9;
}

message CoolingReportResponse {
    bool success = 1;
}